Import code
stfc/fgenerator pull request #2
Opened 2017-01-30 11:31 UTC by rupertford

Ready for review ...

2017-01-30 13:55 UTC, arporter commented
Legally-approved license added to source files.
Repository structured in a form suitable for pypi (although not yet configured for it).
I can get the tests to run (all pass or xfail) by adding fgenerator/src to my PYTHONPATH (and installing fparser using pip).

2017-01-30 13:58 UTC, arporter requested changes
All looks OK - see earlier comment on this request.
My only issue is with having a file named 'subclass.py'. Maybe it should be something more descriptive such as 'fparser_wrapper.py'

2017-01-31 13:42 UTC, rupertford commented
I've changed the name of the file as suggested by Andy.

2017-01-31 13:58 UTC, arporter approved these changes
All tests pass or xfail. File has been re-named as suggested.

2017-01-31 13:58 UTC, arporter commented on src/fgenerator/base.py
> +from fgenerator.fparser_wrapper import OMPDirective
I like this - it's clearer what OMPDirective does now.

2017-01-31 13:59 UTC, merged