Travis integration branch pull request
stfc/fgenerator pull request #6
Opened 2017-02-01 14:35 UTC by rupertford

I'm not completely sure what I've done here but the tests seem to be running on the servers and badges are appearing. I've integrated with travis, coveralls and codeclimate. I'm not sure about how this all links with commits and pull requests, in particular for codeclimate where I've tried to get it to give pep8 information. Anyway I think it is good enough to get going. I don't understand how the badges are useful on branches if they always point to the Master (or at least the first two seeme to do).

2017-02-03 11:29 UTC, arporter requested changes
Changes for travis look good. I can see the test results on the travis site, the coveralls site and the landscape site. Everything works.

Only query is whether we need codeclimate *and* landscape. Are they complementary or just duplication? I can't see the repo on codeclimate so at the least please add a badge/link to it. Please clarify.

2017-02-06 02:25 UTC, rupertford commented
I've added a codeclimate badge as suggested. To answer your question, there is a lot of overlap between landscape and codeclimate. Both have various code quality tests but they use different engines. Essentially, codeclimate works with lots of different languages and landscape is effectively codeclimate for python. I'm trying out both in this project to see which I like best. Of course I might like, and therefore keep, both.

2017-02-06 09:39 UTC, arporter commented
Badge for CodeClimate has been added and works. I now understand why you have both that and Landscape. All OK to merge.

2017-02-06 09:39 UTC, arporter approved these changes

2017-02-06 14:11 UTC, merged